@startuml
class LoginModel {
    + LoginModel(signInManager:SignInManager<IdentityUser>, logger:ILogger<LoginModel>, userManager:UserManager<IdentityUser>)
    + ReturnUrl : string <<get>> <<set>>
    + ErrorMessage : string <<get>> <<set>>
    + <<async>> OnGetAsync(returnUrl:string) : Task
    + <<async>> OnPostAsync(returnUrl:string) : Task<IActionResult>
}
class "IList`1"<T> {
}
class InputModel {
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + RememberMe : bool <<get>> <<set>>
}
PageModel <|-- LoginModel
LoginModel --> "Input" InputModel
LoginModel --> "ExternalLogins<AuthenticationScheme>" "IList`1"
LoginModel +-- InputModel
@enduml
