@startuml
class ResetPasswordModel {
    + ResetPasswordModel(userManager:UserManager<IdentityUser>)
    + OnGet(code:string) : IActionResult
    + <<async>> OnPostAsync() : Task<IActionResult>
}
class InputModel {
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + Code : string <<get>> <<set>>
}
PageModel <|-- ResetPasswordModel
ResetPasswordModel --> "Input" InputModel
ResetPasswordModel +-- InputModel
@enduml
