@startuml
class SetPasswordModel {
    + SetPasswordModel(userManager:UserManager<IdentityUser>, signInManager:SignInManager<IdentityUser>)
    + StatusMessage : string <<get>> <<set>>
    + <<async>> OnGetAsync() : Task<IActionResult>
    + <<async>> OnPostAsync() : Task<IActionResult>
}
class InputModel {
    + NewPassword : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
}
PageModel <|-- SetPasswordModel
SetPasswordModel --> "Input" InputModel
SetPasswordModel +-- InputModel
@enduml
