@startuml
!include .\\Program.puml
!include .\\Startup.puml
!include .\\BusinessLogic\CSVManagement.puml
!include .\\Controllers\DashboardController.puml
!include .\\Controllers\HomeController.puml
!include .\\Data\ApplicationDbContext.puml
!include .\\Data\ApplicationUser.puml
!include .\\Migrations\20211109205933_StateAndChartOnly.puml
!include .\\Migrations\20211109205933_StateAndChartOnly.Designer.puml
!include .\\Migrations\20220405022618_regionUpdate.puml
!include .\\Migrations\20220405022618_regionUpdate.Designer.puml
!include .\\Migrations\20220405035458_yearIntToString.puml
!include .\\Migrations\20220405035458_yearIntToString.Designer.puml
!include .\\Migrations\ApplicationDbContextModelSnapshot.puml
!include .\\Models\Chart.puml
!include .\\Models\ErrorViewModel.puml
!include .\\Models\Region.puml
!include .\\Models\States.puml
!include .\\Areas\Identity\IdentityHostingStartup.puml
!include .\\BusinessLogic\Interfaces\ICSVManagement.puml
!include .\\Models\ViewModels\UploadCSVModel.puml
!include .\\Services\InterfaceModels\ICrud.puml
!include .\\Services\InterfaceModels\IReadOnly.puml
!include .\\Services\Interfaces\IChart.puml
!include .\\Services\Interfaces\IRegion.puml
!include .\\Services\Interfaces\IStates.puml
!include .\\Services\Repos\ChartRepo.puml
!include .\\Services\Repos\RegionRepo.puml
!include .\\Services\Repos\StatesRepo.puml
!include .\\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\obj\Debug\netcoreapp3.1\CPH.AssemblyInfo.puml
!include .\\obj\Debug\netcoreapp3.1\CPH.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Debug\netcoreapp3.1\CPH.RazorAssemblyInfo.puml
!include .\\obj\Debug\netcoreapp3.1\CPH.RazorTargetAssemblyInfo.puml
!include .\\obj\Release\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\obj\Release\netcoreapp3.1\CPH.AssemblyInfo.puml
!include .\\obj\Release\netcoreapp3.1\CPH.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Release\netcoreapp3.1\CPH.RazorAssemblyInfo.puml
!include .\\obj\Release\netcoreapp3.1\CPH.RazorTargetAssemblyInfo.puml
!include .\\Areas\Identity\Pages\Account\AccessDenied.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ExternalLogin.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ForgotPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Login.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Logout.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Register.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ResetPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\CPH.AssemblyInfo.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\CPH.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\CPH.RazorAssemblyInfo.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\CPH.RazorTargetAssemblyInfo.puml
!include .\\Areas\Identity\Pages\Account\Manage\Email.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\Index.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ManageNavPages.puml
!include .\\Areas\Identity\Pages\Account\Manage\SetPassword.cshtml.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\_ViewImports.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\_ViewStart.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\_ViewStart.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Dashboard\CreateChart.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Dashboard\CreateRegion.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Dashboard\UploadCSV.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Home\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Home\Privacy.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\Error.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\_Layout.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\_LoginPartial.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Dashboard\UploadCSV.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Home\Chart.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Home\Index.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Home\Privacy.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Home\UploadCSV.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Shared\Error.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Shared\_Layout.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Shared\_LoginPartial.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Views\Shared\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\_ViewStart.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\_ViewImports.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\_ViewStart.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\_ViewStart.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Dashboard\UploadCSV.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Home\Chart.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Home\Index.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Home\Privacy.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Home\UploadCSV.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Shared\Error.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Shared\_Layout.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Shared\_LoginPartial.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Views\Shared\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\AccessDenied.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ExternalLogin.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ForgotPassword.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Login.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Logout.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Register.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ResetPassword.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\AccessDenied.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ExternalLogin.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ForgotPassword.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Login.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Logout.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Register.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ResetPassword.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\_ViewStart.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\Email.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\SetPassword.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\Email.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\Index.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\SetPassword.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\AccessDenied.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\ExternalLogin.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\ForgotPassword.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Login.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Logout.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Register.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\ResetPassword.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\_ViewImports.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Manage\Email.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Manage\Index.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Manage\SetPassword.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml.g.puml
!include .\\obj\Release\netcoreapp3.1\win-x64\Razor\Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml.g.puml
@enduml
